# QUESTION 1.

**Prime factors** of a given positive integer $x$ is the set of numbers $Y$ such that $y \in Y$ satisfy the following two conditions: 

1) $y$ is a prime number

2) $x$ is perfectly divisible by $y$

For example, the set of prime factors of 13195 is $\{5, 7, 13, 29\}$. The largest prime factor here is $29$. 

Write a function **`largest_prime_factor`** the takes in as input a positive integer `x` and returns the _largest prime factor_ of the number `x`.

# QUESTION 2.

Write a function **`print_pyramid`** that takes one integer input `n` and prints a pyramid of `n` rows with **increasing width**, such that $i^{th}$  row prints number $i \in [1, n]$ as shown below. 

The input `n` must be an integer from `1` to `9` i.e. $n \in [1, 9]$. For any other input, **`raise`** an appropriate Error with an informative error message. 

Use the provided **`print_same_line(x)`** function to print on the same line and the provided **`go_to_newline()`** function to go to next line. 


<hr />


**Example 1**: 

_Input_: `n=3` 

_Output_: 
``     
       1
      222
     33333``

**Example 2:** 

_Input_: `n=8` 

_Output_: 
``     
       1
      222
     33333
    4444444
   555555555
  66666666666
 7777777777777
888888888888888``

<hr/>

In [ ]:
def print_same_line(x):
    print(x, end='')
    
def go_to_newline():
    print()

# QUESTION 3.

Write a function **`print_inverse_pyramid`** that takes one integer input `n` and prints a diamond of `n` rows of **decreasing width**, such that $i^{th}$ row prints number $(n-i) \in [1, n]$ as shown below.

The input `n` must be an integer from `1` to `9` i.e. $n \in [1, 9]$. For any other input, **`raise`** an appropriate Error with an informative error message. 

Use the provided **`print_same_line(x)`** function to print on the same line and the provided **`go_to_newline()`** function to go to next line. 

<hr />


**Example 1**: 

_Input_: `n=3` 


_Output_ ``:
     33333
      222
       1 ``

**Example 2:** 

_Input_: `n=8` 

_Output_: 

``     
888888888888888
 7777777777777
  66666666666
   555555555
    4444444
     33333
      222
       1
``

<hr/>

In [ ]:
def print_same_line(x):
    print(x, end='')
    
def go_to_newline():
    print()

# QUESTION 4.

Write a function **`print_diamond`** that takes one integer input `n` and prints a diamond of `2*n - 1` rows as shown below.

The input `n` must be an integer from `1` to `9` i.e. $n \in [1, 9]$. For any other input, **`raise`** an appropriate Error with an informative error message. 

Use the provided **`print_same_line(x)`** function to print on the same line and the provided **`go_to_newline()`** function to go to next line. 

Input: `3`

Output
``:
  1
 222
33333
 222
  1``
  
  
Input: `8`

Output: ``     1
      222
     33333
    4444444
   555555555
  66666666666
 7777777777777
888888888888888
 7777777777777
  66666666666
   555555555
    4444444
     33333
      222
       1
``


<hr />

In [ ]:
def print_same_line(x):
    print(x, end='')
    
def go_to_newline():
    print()